project_name: castsponsorskip
builds:
  - env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "7"
archives:
  - format: tar.gz
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  - repository:
      owner: gabe565
      name: homebrew-tap
      token: '{{ .Env.HOMEBREW_TOKEN }}'
    folder: Formula
    install: |
      bin.install "{{ .ProjectName }}"
dockers:
  - &dockers
    image_templates:
      - ghcr.io/gabe565/{{ .ProjectName }}:{{ .Version }}-amd64
    use: buildx
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
      - "--platform=linux/amd64"
  - <<: *dockers
    image_templates:
      - ghcr.io/gabe565/{{ .ProjectName }}:{{ .Version }}-armv7
    goarch: arm
    goarm: 7
    build_flag_templates:
      - "--platform=linux/arm/v7"
  - <<: *dockers
    image_templates:
      - ghcr.io/gabe565/{{ .ProjectName }}:{{ .Version }}-arm64v8
    goarch: arm64
    build_flag_templates:
      - "--platform=linux/arm64/v8"
docker_manifests:
  - &docker_manifests
    name_template: ghcr.io/gabe565/{{ .ProjectName }}:latest
    image_templates:
      - ghcr.io/gabe565/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/gabe565/{{ .ProjectName }}:{{ .Version }}-armv7
      - ghcr.io/gabe565/{{ .ProjectName }}:{{ .Version }}-arm64v8
  - <<: *docker_manifests
    name_template: ghcr.io/gabe565/{{ .ProjectName }}:{{ .Version }}
  - <<: *docker_manifests
    name_template: ghcr.io/gabe565/{{ .ProjectName }}:{{ .Major }}
  - <<: *docker_manifests
    name_template: ghcr.io/gabe565/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}
nfpms:
  - id: packages
    vendor: Gabe Cook
    homepage: https://github.com/gabe565/CastSponsorSkip
    description: A Go program that skips sponsored YouTube content on all local Google Cast devices
    license: GPL-3.0
    maintainer: Gabe Cook <gabe565@gmail.com>
    formats:
      - deb
      - rpm
    contents:
      - src: ./castsponsorskip.service
        dst: /etc/systemd/system/castsponsorskip.service
        type: config
publishers:
  - name: fury.io
    ids:
      - packages
    dir: "{{ dir .ArtifactPath }}"
    cmd: curl -sf -Fpackage=@{{ .ArtifactName }} https://{{ .Env.FURY_TOKEN }}@push.fury.io/gabe565/
